version: "3.7"
services:
        service1:
                image: mihsana/project-service1
                build: ./service1
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp
                depends_on:
                        - "mysql"
                environment:
                        SECRET_KEY: ${SECRET_KEY}
                        DATABASE_URI: ${DATABASE_URI}
                deploy:
                        replicas: 2 


        service2:
                image: mihsana/project-service2
                build: ./service2
                ports:
                        - target: 5001
                          published: 5001
                          protocol: tcp
                 
                deploy:
                        replicas: 2

        service3:
                image: mihsana/project-service3
                build: ./service3
                ports:
                        - target: 5002
                          published: 5002
                          protocol: tcp

                deploy:
                        replicas: 2

        service4:
                image: mihsana/project-service4
                build: ./service4
                ports:
                        - target: 5003
                          published: 5003
                          protocol: tcp
                deploy:
                        replicas: 2


        mysql:
                image: mysql
                container_name: mysql
                ports:
                        - target: 3306
                          published: 3306
                          protocol: tcp
                       
                environment:
                        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
                        MYSQL_DATABASE: project-db
                volumes:
                        - type: volume
                          source: db-data
                          target: /var/lib/mysql

volumes:
        db-data:
